# Generated by Django 4.2.23 on 2025-08-13 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sku', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='sku',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='collection',
            field=models.ManyToManyField(blank=True, null=True, to='core.collection'),
        ),
    ]
