# Generated by Django 4.2.23 on 2025-08-14 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='collection',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
