# Generated by Django 4.2.23 on 2025-08-19 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='img',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='variantoptionvalue',
            unique_together={('variant', 'option_value')},
        ),
    ]
