# Generated by Django 4.2.23 on 2025-08-19 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_productvariant_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
