# Generated by Django 4.2.23 on 2025-08-14 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_voucher_promotion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promotion',
            old_name='categories',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='promotion',
            old_name='collections',
            new_name='collection',
        ),
        migrations.RenameField(
            model_name='promotion',
            old_name='products',
            new_name='product',
        ),
    ]
