# Generated by Django 4.2.23 on 2025-08-14 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_categories_promotion_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='slug',
            field=models.SlugField(default='default-slug', max_length=100, unique=True),
        ),
    ]
