# Generated by Django 4.2.23 on 2025-08-14 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_promotion_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
