"""
Django settings for ecom project.

Generated by 'django-admin startproject' using Django 4.2.23.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
from decouple import config
from dotenv import load_dotenv
load_dotenv()
#MinIO


#
PREFIX_URL = os.environ.get("PREFIX_URL")
API_VERSION = os.environ.get("API_VERSION")

#
IS_DEV = os.environ.get('IS_DEV', 0)

#Database
MYSQL_DATABASE_NAME = os.environ.get("DB_NAME")
MYSQL_DATABASE_USER = os.environ.get("DB_USER")
MYSQL_DATABASE_PASSWORD = os.environ.get("DB_PASSWORD")
MYSQL_DATABASE_HOST = os.environ.get("DB_HOST")
MYSQL_DATABASE_PORT = os.environ.get("DB_PORT")

#kafka
LIST_BROKERS = os.environ.get('LIST_BROKERS').split(',')
KAFKA_TOPIC = os.environ.get('KAFKA_TOPIC')

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--hchd8vtd!q0xl-z+mu@4&n%!uax+)d1p$7i7ti$rvc#h@#3^l'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.staticfiles',

    'apps.catalogue',
    'apps.auths',
    'rest_framework',
    'storages',
    'vnpay',

    'django_filters',
    'apps.shared',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # "apps.middleware.request_middleware.RequestMiddleware",
]



REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [],
    'UNAUTHENTICATED_USER': None, 
    'UNAUTHENTICATED_TOKEN': None,

    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.OrderingFilter',
        'rest_framework.filters.SearchFilter',
    ),
    'DEFAULT_PAGINATION_CLASS': 'apps.shared.drf.pagination.StandardResultsSetPagination',
    'PAGE_SIZE': 10,
    'SEARCH_PARAM': 'search',
    'ORDERING_PARAM': 'ordering',
    'DATETIME_FORMAT': '%Y-%m-%d %H:%M:%S',
    'DATE_FORMAT': '%Y-%m-%d',
}
APPEND_SLASH = False # Bỏ dấu "/" cuối url

MINIO_ENDPOINT = config("MINIO_ENDPOINT")
MINIO_ACCESS_KEY = config("MINIO_ACCESS_KEY")
MINIO_SECRET_KEY = config("MINIO_SECRET_KEY")
MINIO_BUCKET_NAME = config("MINIO_BUCKET_NAME")
MINIO_BASE_URL = config("MINIO_BASE_URL")
MINIO_LOCATION = config("MINIO_LOCATION")
MINIO_PORT = config("MINIO_PORT")


STORAGES = {
    "default": {
        "BACKEND": "apps.utils.storages.MinioMediaStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

ROOT_URLCONF = 'ecom.urls_base'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
            'django.template.context_processors.debug',
            'django.template.context_processors.request',
            ],
        },
    },
]

WSGI_APPLICATION = 'ecom.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': MYSQL_DATABASE_NAME,
        'USER': MYSQL_DATABASE_USER,
        'PASSWORD': MYSQL_DATABASE_PASSWORD,
        'HOST': MYSQL_DATABASE_HOST,
        'PORT': MYSQL_DATABASE_PORT,
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        }
    }
}




# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

# Ngôn ngữ mặc định
# LANGUAGE_CODE = 'en-us'
LANGUAGE_CODE = 'vi'

# Múi giờ
TIME_ZONE = 'Asia/Ho_Chi_Minh'

# Bật dịch ngôn ngữ
USE_I18N = True

# Bật timezone
USE_TZ = True

# Bật định dạng theo locale
USE_L10N = True

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
